# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-01 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regform', '0002_member_member_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='other_health_work',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='member',
            name='other_other_work',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='member',
            name='full_name',
            field=models.CharField(max_length=60, verbose_name='Full name:'),
        ),
    ]
