# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-02 08:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regform', '0003_auto_20171101_1549'),
        ('regform', '0003_auto_20171101_1655'),
    ]

    operations = [
    ]
